### ISSUE TITLE
Missing Euro Version of TLA-7/Ave-6 Type A1 TuLEP

### ISSUE THREAD

**Issue by zsc4** [BluelightningSC4/Network-Addon-Mod#135]
When Euro textures are selected, the TLA-7/Ave-6 Type A1 TuLEP still shows up with the American-style textures.

Also, there are two versions of the file z2_NWM_Euro_TRM_TuLEP.dat - one in the NewTextures - ESSENTIAL folder, and one in the NWM\NWM_v2_Euro_Textures_Mod folder.  They are of different sizes, and the second one is more recent.  It appears that one of these files should be removed; probably the first.  Due to file loading order, it is being overwritten.

**Comment by TarkusSC4** [comment]
One now exists and is included in the Euro texture set for NAM 33.  As TuLEPs actually aren't part of the NWM and can be installed separately, I've moved the version from the NWM folder over to the NewTextures - ESSENTIAL folder and replaced the one there in the process.
