### ISSUE TITLE
L0 Diag RHW-4 under L1 Ortho RHW-8S Deconverts RHW-4

### ISSUE THREAD

**Issue by noahclem** [BluelightningSC4/Network-Addon-Mod#146]
With starters on both sides no amount of clicking around, etc, could stop the RHW-4 from deconverting to RHW-2.

**Comment by TarkusSC4** [comment]
This one appears to be more stable (though still temperamental) in NAM 33 PR, to the point of being largely usable.  The planned MetaRUL upgrade (sometime post-NAM 33) will solve it entirely.
