### ISSUE TITLE
Broken FARHW 6S pieces

### ISSUE THREAD

**Issue by Brockist** [BluelightningSC4/Network-Addon-Mod#212]
Here, as you can see, the paths for the "RHW-6S FA-to diagonal-outer-curve" piece are off by quite a bit, not only that, but the "L0 RHW-6S FIller (Diag)"'s paths are off by a bit too, along with the "RHW-6S Smooth Outer Curve / Inner curve" too. 

RHW-6S FA-to diagonal-outer-curve VV
![rhw 6 farhw bug](https://cloud.githubusercontent.com/assets/5060228/2924265/0d753d50-d72e-11e3-9cde-9ceae1427579.png)

RHW-6S Smooth Outer Curve / Inner curve VV
![rhw 6 diag bug](https://cloud.githubusercontent.com/assets/5060228/2924266/10d7c198-d72e-11e3-9b8d-dd8f0b3c22be.png)

**Comment by TarkusSC4** [comment]
This one has now been fixed, with update to Gogs depository on 15 Aug 2015.  Fix will go live in NAM 33 official release.
