### ISSUE TITLE
RHW-4 & MIS-1 Starters and Immediate Diagonals

### ISSUE THREAD

**Issue by BluelightningSC4** [BluelightningSC4/Network-Addon-Mod#214]
Attempting to drag a ortho-diag curve out of a starter does not cause the starter to convert to the blend piece and also does not convert the straight-diag tile into the top blend piece. Was a feature in previous RHW versions, seems to have been dropped recently

**Comment by TarkusSC4** [comment]
Fixed after NAM 33 Alpha 3.
