### ISSUE TITLE
Turbo Roundabouts Texturing Issues

### ISSUE THREAD

**Issue by memo33** [BluelightningSC4/Network-Addon-Mod#215]
Reported by mgb204: http://sc4devotion.com/forums/index.php?topic=1444.msg483538#msg483538

![](http://i991.photobucket.com/albums/af39/MGB204/NAMTABug_zpsf27e76f4.jpg~original)

Quote:
> The red circles indicate a tile the roundabout occupies but that shows no texture. This error occurs with both LHD + EU Textures and RHD + US Textures. The odd thing is that the preview shows correctly, so the texture is presumably present?

> The yellow circle is a small texture problem, only noticed with LHD + EU Textures, again the preview is correct but the plopped piece is not.

**Comment by TarkusSC4** [comment]
I've fixed the missing bites on the RD-6 x ARD-3 4-way roundabouts.  Will need to dive into the LHT Euro textures to find what's happening there.

**Comment by TarkusSC4** [comment]
Now fixed all the way.  The LHT support file for the Turbo Roundabouts was missing the model at 0x5b880300, which caused this.
