### ISSUE TITLE
L2 8C E1 Ramps showing L2 8C B1 Models

### ISSUE THREAD

**Issue by GanaramInukshuk** [BluelightningSC4/Network-Addon-Mod#223]
Reported by: NielsC007
Issue: Models
Link: http://sc4devotion.com/forums/index.php?topic=990.msg496681#msg496681

**Comment by TarkusSC4** [comment]
The exemplars were pointing toward the B1 ramp instead of the E1.  All models, textures, and paths were otherwise fine. Fixed with update to Gogs depository on Aug. 2nd, 2015.
