### ISSUE TITLE
Unconverted 2×128×128 Overhangs to 128×256 (from Teaservid 7)

### ISSUE THREAD

**Issue by GanaramInukshuk** [BluelightningSC4/Network-Addon-Mod#225]
This goes hand-in-hand with all of Maarten's texture sets and with a lot of Ramp Interfaces; all Ramp Interface overhangs need to (eventually) be converted to using 128×256 overhangs instead of a double 128×128 overhang. The telltale sign of this bug is texture stretching with Maarten's texture sets.

Old overhang textures (textures ending with 9) will end up being used with L1 elevated ramps as wealth textures, due to how the IIDs for these ramps (IIDs ending with 9) are the same. This is addressed in Change 11 in Teaservid 7: https://www.youtube.com/watch?v=uvxFrKI9lCs

These are the ones from teaservid 7 and these apply to all height levels; there are many more ramps with this issue; if found, then please open a new issue with the same tags and title it "Unconverted overhangs".
 - RHW-2 A1
 - RHW-4 A1 Outside

**Comment by TarkusSC4** [comment]
Did a whole bunch of file cleanup and converted every last 128x128 dual overhang I could find.  Updated Gogs on 12 Aug 2015 with the resultant files.  I'm going to call this one closed for now.
