### ISSUE TITLE
L1/L2 DDRHW-4 still uses code from L2/L3 setup

### ISSUE THREAD

**Issue by GanaramInukshuk** [BluelightningSC4/Network-Addon-Mod#227]
Addressed in Teaservid 7, change 8: https://www.youtube.com/watch?v=uvxFrKI9lCs

The newly lowered DDRHW-4 will still create crossings with L1 RHWs and will not be able to cross with L3 RHWs.

**Comment by TarkusSC4** [comment]
Started on this one.
