### ISSUE TITLE
Disconnector cannot eat FlexFlys or MHW-based starters

### ISSUE THREAD

**Issue by GanaramInukshuk** [BluelightningSC4/Network-Addon-Mod#228]
Current Disconnector RUL0 code lacks any Dirtroad×GroundHighway or Dirtroad×Highway intersections, meaning that FlexFlys and certain elevated RHW starters cannot be disconnected using the Disconnector.

http://sc4devotion.com/forums/index.php?topic=17038.msg496523#msg496523

Solution: give it its own button.

**Comment by TarkusSC4** [comment]
RUL0 changes made on my end.  Just needs the actual button graphics, at which point we can add the icon exemplar.
