### ISSUE TITLE
Unconverted Overhangs (6S E1 Inside and 8S D1 Inside Ramps)

### ISSUE THREAD

**Issue by GanaramInukshuk** [BluelightningSC4/Network-Addon-Mod#229]
![image](https://cloud.githubusercontent.com/assets/5506045/9028093/2ce8597c-3922-11e5-861b-f68c0f72f54a.png)

6S E1 Inside: Textures are unconverted from 128×128, but uses 128×256 models; models are also backwards on onramp but not on offramp
8S D1 Inside: Models are unconverted from 128×128, but uses 128×256 textures; affects offramp and onramp

(The hexagon is an easter egg; don't fix that one)

**Comment by TarkusSC4** [comment]
In the case of the 6S E1, my investigation has turned up that the textures actually are converted (the onramp model was backwards) but there's duplicate textures at the same IIDs in the L1-L4 6S .dats that aren't, and they're loading later and interfering.

**Comment by TarkusSC4** [comment]
Fixed with Gogs update to L0 RHW-6S, L0 RHW-8S, and L1-L4 RHW-6S .dat files on 3 Aug 2015.
