### ISSUE TITLE
Elevated RHW-4 to MIS IID Allocation Conflict

### ISSUE THREAD

**Issue by GanaramInukshuk** [BluelightningSC4/Network-Addon-Mod#235]
Current IID allocation for elevated RHW-4 to MIS IIDs have it such that they eat more space than what is allowed for the draggable width transitions.

IID allocation for proposed width transitions have it such that the 6th digit is Tile ID (0x577NMTWZ, similar with the FlexRamps), but the puzzle-based pieces (0x577NMXYH) use X-coordinates 0-8, conflicting with the proposed use of Tile IDs 3-F.

L1 RHW-4 to MIS Transition IIDs (starting with 0x57732): 400, 390, 380, ??? (there's a fourth tile missing)
L2 RHW-4 to MIS Transition IIDs (starting with 0x57732): 800, 700, 690, 680

Proposed solution is to move these pieces to X-coordinate 0-3 to make way for draggable transitions; possibly to the following:

L1 RHW-4 to MIS Transition IIDs (starting with 0x57732): 001, 011, 101, 111
L2 RHW-4 to MIS Transition IIDs (starting with 0x57732): 002, 012, 102, 112

This puts them more in line with what Maarten's L1/L2 height transitions use for IIDs.

**Comment by GanaramInukshuk** [comment]
NOTE: There may still be enough room even if this is the case, as these transitions are smaller. However, they still don't fit the IID scheme that the other WTs follow.

**Comment by GanaramInukshuk** [comment]
Recent change to the corresponding RUL0 section has fixed the code-related part of this issue, leaving behind the reassigned .DAT entries to take care of. Once the changes have been added to the main .DAT files, this issue can be closed.

**Comment by TarkusSC4** [comment]
And now the .DAT entries have been updated.  Issue closed.
