### ISSUE TITLE
Unconverted Overhangs (Elevated 6S D1 Inside)

### ISSUE THREAD

**Issue by GanaramInukshuk** [BluelightningSC4/Network-Addon-Mod#237]
![image](https://cloud.githubusercontent.com/assets/5506045/9046804/2186eefc-39e2-11e5-94f9-b3438d38dff3.png)

Several issues:
 - Missing textures
 - Mismatched texture and model sizes
 - Models reference incorrect texture IIDs, including L0 wealth textures

**Comment by TarkusSC4** [comment]
Fixed with update to Gogs depository on 3 Aug 2015.  L1-L4 RHW-6S .dat files updated.
