### ISSUE TITLE
45 Degree FlexFly L2 cannot cross, degenerates to L0 RHW2

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#239]
![3sc4](https://cloud.githubusercontent.com/assets/13636565/9053871/ef21f062-3a48-11e5-9324-ad2bf788a1a6.PNG)

How does this happen and is it being fixed? I was trying to cross a L0 RHW6S

**Comment by GanaramInukshuk** [comment]
Issue replicated; affects base networks, regardless of RHW widths/heights involved (INRUL14)

Interim solution is diagonal RHW half-dragging.

**Comment by TarkusSC4** [comment]
Actually, this doesn't even look like a FLEXFly issue.  It looks like a base network OxD crossing issue.  This one may not get fixed until the MetaRUL system is fully in place.

**Comment by TarkusSC4** [comment]
Normally, the base INRUL14 code that converts that base setup to the OxD RHW-2 x RHW-2 intersection should kick in, and then the rest of the overrides wiith it.  But somehow, that code appears to be getting interfered with by the FLEXFly.

**Comment by GanaramInukshuk** [comment]
There's extra INRUL14 code that accounts for RHW diagonal xings one tile directly after a diagonal FlexFly's diagonal end, but apparently not one tile away from it. Could be INRUL interference or load order problems or it's just not been accounted for properly.

**Comment by TarkusSC4** [comment]
I managed a partial fix, converting the wacky T-intersections into something that could be overridden properly, but the darn orth-diag transition on the other side, despite everything being correct in the INRULs, is being the most stubborn, obnoxious thing ever.  Even an inelegant solution involving RUL2 produces no stable result for that stupid tile.

**Comment by memo33** [comment]
I'm in the process of fixing this.
