### ISSUE TITLE
Override not working properly on MRC 90 degree R2

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#240]
Pretty self explainatory, override fails to complete on 90 degree R2, even when starters placed on either end to initiate overrides 45 degrees at a time. I haven't tried it with RHW-4 but this happens with RHW-6S

![mrcoverridefail](https://cloud.githubusercontent.com/assets/13636565/9074674/d9fa74f2-3ad9-11e5-948f-9eb923029d7d.PNG)

**Comment by GanaramInukshuk** [comment]
Feature not available, as the R2 90deg curve is only designed to work for RHW-4 and MIS only.

**Comment by TarkusSC4** [comment]
This one has been brought up before, but the last time, eggman121 stated on the NAM 33 Pre-Release thread that he considered this to be [too tight of a curve for a 6S, anyway](http://sc4devotion.com/forums/index.php?topic=17038.msg496527#msg496527), so this probably isn't going to be a feature, and the LTEXT is the only problem (already posted as #241 ).  I'm going to close this one down.
