### ISSUE TITLE
Placing Starters Fail, one side does tile vanishing act

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#242]
Why would dragging from a starter work on one side and not the other on a RHW-6s bridge? It worked fine on the left side, but the tiles vanished on the right side. I placed the starter on the tile next to the beginning of the rails in both cases

![whythis](https://cloud.githubusercontent.com/assets/13636565/9076331/231a21c2-3aef-11e5-95bf-615b1fbff83d.PNG)

**Comment by GanaramInukshuk** [comment]
Issue replicated with NAM 33 PR1. Interim solution: put starters farther away. Marked as Defcon 5 RUL issue.

**Comment by TarkusSC4** [comment]
It's not a problem using the RHW-4, and is strictly limited to the 6S.  Likely, there's something up with the way the 6S interacts with the MHW/RHW transition.
