### ISSUE TITLE
RHW Manual Update?

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#246]
Just asking if there is a RHW manual (and other documentation) update in the works, as it has not been updated since 31.2. Also why does the RHW manual PDF file prompt us to print it?

**Comment by GanaramInukshuk** [comment]
Actually taking the time to update the manuals will take more time and resources than any of us is willing to put in, and it's so big that it's basically unwieldy to even edit.

Everything pertaining to documentation is explained in here: https://simtarkus.wordpress.com/2015/08/03/whats-up-with-the-nam-documentation-august-2015-edition/
