### ISSUE TITLE
Unconverted overhangs for LHT setups

### ISSUE THREAD

**Issue by GanaramInukshuk** [BluelightningSC4/Network-Addon-Mod#247]
http://sc4devotion.com/forums/index.php?topic=990.msg496983#msg496983

Unconverted overhangs affect LHT as much as any of the RHT texture sets.

**Comment by TarkusSC4** [comment]
I'm pretty far in with this one now.  Should be finished shortly.

**Comment by TarkusSC4** [comment]
RHW LHT file has been updated.  The big thing was that non-overhang versions of overhang tiles that didn't even need to be in the LHT support file, which have been removed.
