### ISSUE TITLE
RHW-6S B2 Ramp Missing Path

### ISSUE THREAD

**Issue by GanaramInukshuk** [BluelightningSC4/Network-Addon-Mod#250]
![image](https://cloud.githubusercontent.com/assets/5506045/9162290/059d54e8-3efa-11e5-885c-501169f32e6c.png)

There's a very small path missing on the corner of tile 5 on the 6S B2 Ramp, making the inner path on the branch undrivable. I'm marking this as a Defcon 4 path issue with delay since the outer path is still drivable, making the entire ramp still, well, functional.

This also affects the Type A2 Wide Ramp, since tile 5 is also used with the wide ramp.

**Comment by TarkusSC4** [comment]
Went ahead and knocked this one out with a Gogs update on 14 Aug 2015.
