### ISSUE TITLE
L1 90 degree FlexFly issue

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#253]
![flexfail](https://cloud.githubusercontent.com/assets/13636565/9216980/c7b0cdd0-408f-11e5-8f05-580cb9b6e925.PNG)
Looks like it's a texturing issue. So far it only happens with 6S

**Comment by GanaramInukshuk** [comment]
It's the 6S overhangs getting in the way with the pillars. I wouldn't recommend having a FlexFly that close to an RHW-6S because of that.

Issue closed.
