### ISSUE TITLE
FARHW file being installed twice

### ISSUE THREAD

**Issue by TarkusSC4** [BluelightningSC4/Network-Addon-Mod#258]
The file RealHighway_FractionalAngleNetworking.dat is being installed twice, with one copy in the root Network Addon Mod\Real Highway Mod folder, the other in Network Addon Mod\Real Highway Mod\FARHW.

This one has likely existed for awhile, well preceding NAM 33 PR.

**Comment by TarkusSC4** [comment]
Will wait until other installer developments (pertaining to SLURP and the z___NAM folder) are in place.

**Comment by zsc4** [comment]
As soon as I can get the current version of the installer release from the clutches of Git, and also round up a few more brain cells (three or four should do it), I'll fix this.

**Comment by TarkusSC4** [comment]
Thanks, Steve!

**Comment by zsc4** [comment]
Removed duplicate insertion line from installer.

**Comment by zsc4** [comment]
Closed #258
