### ISSUE TITLE
L2 6C & 8C blending together?

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#263]
![hmm](https://cloud.githubusercontent.com/assets/13636565/9399398/a28a1c7a-4781-11e5-8574-18bf1f786ac9.PNG)

Is this even covered yet? I looked and could not find any issue relating to this

**Comment by TarkusSC4** [comment]
That's not a 6C there . . . you will occasionally see this sort of thing happen with the stubs.  It's a pretty minor thing.

**Comment by GanaramInukshuk** [comment]
Only a börked-up section of stub override would cause this to happen. I have a vague idea where it'd be, and it'd in the current stub stabiliser code section.

Hence why stub stabilisation should be a thing for later on (or rather a rewrite of current code).

**Comment by TarkusSC4** [comment]
There are no stub corrections for any of the elevated RHWs at the moment.  I'm also unable to replicate this issue at all.  The only stub issue I encounter on the L2 8C is with occasional reversion to L0 8C.

**Comment by TarkusSC4** [comment]
I've now updated the stub correction overrides, so this one definitely isn't an issue anymore.

**Comment by memo33** [comment]
This used to happen in proximity of a starter because of the way the wider network overrides were initiated. I'm not sure whether those starters were ever changed to unique falsies, but it had been brought up for consideration.
