### ISSUE TITLE
L2 RHW6S D1 missing models/textures when DRI'd

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#264]
![nod1](https://cloud.githubusercontent.com/assets/13636565/9399519/ab323f40-4783-11e5-8093-0612eb4c80e4.PNG)
When I did a DRI for the L2 RHW-6S D1 (supported by default) ramp, this happened. I had to put the correct starters on either end in order to fix it, something I should not have had to do

**Comment by TarkusSC4** [comment]
I can't replicate this particular one with the current dev files, so at most, this might exist in the NAM 33 PR but has already been fixed in the preparation for the official release.
