### ISSUE TITLE
MRCs not being slope tolerant as labeled

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#266]
I was trying to build a 45 degree MRC with gradual 2m slopes and it was acting like a normal curve, not being very slope tolerant
![mrcfail](https://cloud.githubusercontent.com/assets/13636565/9427106/9fb64894-4938-11e5-88fc-0650b4cfd1fb.PNG)

**Comment by TarkusSC4** [comment]
Actually, if you look close there, you'll see there is a slight slope in the midst of the piece--it's going downhill.  That qualifies as slope tolerant, so the piece is acting as advertised.
