### ISSUE TITLE
Please explain THIS

### ISSUE THREAD

**Issue by LReyome254** [BluelightningSC4/Network-Addon-Mod#270]
I was attempting to do an 8S D1 Inside and this happened, it reappeared after using disconnector and redragging. Can this be explained?

![8sid1wtf](https://cloud.githubusercontent.com/assets/13636565/9592658/fef6a638-5012-11e5-990a-ff5d04ac5d23.PNG)

**Comment by GanaramInukshuk** [comment]
Issue already reported. Closed.

**Comment by TarkusSC4** [comment]
Specifically, it's a duplicate of #229, which Ganaram reported back on August 2nd.  Fixed on our end August 3rd.  Also, not a very helpful title.
