### ISSUE TITLE
Shared-Tile NWM Diagonals (RD-4 and OWR-4) Broken

### ISSUE THREAD

**Issue by TarkusSC4** [BluelightningSC4/Network-Addon-Mod#271]
Reported by Moonraker0 on the [SC4D NAM33 PR thread](http://sc4devotion.com/forums/index.php?topic=17038.msg499320#msg499320).  The diagonals for the RD-4 and OWR-4, which operate on a shared-tile rather than split-tile basis, seem to no longer override for some inexplicable reason.  One of the orth-diag tiles aligning with the shared portion is also not showing up for some reason.

![Issue](http://images.akamai.steamusercontent.com/ugc/642119685363007350/058134D63AFDC87D85537B48BE6AD475F3457AB6/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|1024:576&composite-to=*,*|1024:576&background-color=black)

**Comment by TarkusSC4** [comment]
I've gone through and implemented eggman121's changes to revert 0x5f040400 references to 0x00015600, and, correspondingly, in the OWR Advanced INRUL, 0x5f940400 to 0x09015600.  However, coming back from diag to orth, the inner corner doesn't want to override properly back to the ortho RD-4/OWR-4, indicating there's also a RUL2 component to this one, inexplicably.  I'll have to do further investigation to solve it.

**Comment by memo33** [comment]
This change was introduced in commit 34028f7 and was meant for metarules. You can probably just comment out the entire block of code.

**Comment by TarkusSC4** [comment]
IIRC, there was a similar section of code in both the Road and OWR Advanced INRULs dating back to Maxis.  I've reverted the IID 0x0N015600 (N being network code) with the proper rotations, and fixed up the NWM RUL2 code to handle the future MetaRUL-related IID, as well as the inner corner issue.  We'll be able to switch things over easily without NWM disruptions when the time comes.
