### ISSUE TITLE
L0 RHW-4 and STR intersections missing override

### ISSUE THREAD

**Issue by swordmasterSC4** [BluelightningSC4/Network-Addon-Mod#93]
RHW-4 and STR OxD and DxD intersections missing override. OxO stability issue (wrong zoom texture?)

![Clipboard-2](https://f.cloud.github.com/assets/3756773/219973/5550d664-8551-11e2-966f-9dec5b984ea6.jpg)

![Clipboard-1](https://f.cloud.github.com/assets/3756773/219972/506c5ede-8551-11e2-8302-cbf537cbe36c.jpg)

**Comment by TarkusSC4** [comment]
This one has since been fixed.
